import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import styles from "@/app/page.module.css";
import Link from "next/link";
import { Counter } from "@/components/Counter";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, }: {
  children: React.ReactNode
}) {
  console.log("Home layout rendered");

  return (
    <html lang="en">
    <body className={inter.className}>
    <nav>
      <ul className={styles.menu}>
        <li>
          <Link href="/using-useRouter-directly/foo">Using useRouter directly</Link>
        </li>
        <li>
          <Link href="/passing-router-via-context/foo">Passing router via context</Link>
        </li>
        <li>
          <Link href="/passing-useRouter-as-prop/foo">Passing useRouter as prop</Link>
        </li>
      </ul>
    </nav>
    <Counter/>
    {children}
    </body>
    </html>
  )
}
